config/routes.rb
Rails.application.routes.draw do
  get 'search/search', as: :search
  get 'search/suggest'

  get 'merchants/index'

end

app/models/merchant.rb
require 'elasticsearch/model'

class Merchant < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_and_belongs_to_many :specializations, after_add:    [ lambda { |a,c| a.__elasticsearch__.index_document } ],
                          after_remove: [ lambda { |a,c| a.__elasticsearch__.index_document } ]
  has_many :openings

  enum status: [:active, :inactive]
  enum gender: [:male, :female, :other]

  scope :available, -> { joins(:openings).where('openings.end_time > ? and openings.status = ?', Time.now, 1) }

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false'  do
      indexes :name, type: :string
      indexes :about, type: :string
      indexes :avg_rating, type: :float
      indexes :price, type: :float
      indexes :specializations do
        indexes :id, type: :integer
      end
      indexes :suggest, type: 'completion',index_analyzer: 'simple',
          search_analyzer: 'simple',
          payloads: true
    end
  end

  def self.suggest(query)
    Merchant.__elasticsearch__.client.suggest(index: Merchant.index_name, body: {
        suggestions: {
            text: query,
            completion: {
                field: 'suggest',
                size: 20
            }
        }
    })
  end
  def as_indexed_json(options={})
    suggest= {
        suggest: {
            input: [self.name, self.about, self.specializations],
            output: self.name,
            payload: {
                name: self.name,
                about: self.about,
                specializations: self.specializations
            }
        }
    }
    self.as_json(
        only: [:name, :about, :avg_rating, :price, :review_count],
        include: {
            specializations: {only: [:id, :name] }
        }
    ).merge(suggest)
  end


  def self.search(query, sort_column, sort_direction)
    __elasticsearch__.search(
          query: {
              query_string: {
              query: "*#{query}*"
          }},
          :sort =>
              [{sort_column => { order: sort_direction }}]
    )
  end

  def self.filter(filters,sort_column, sort_direction)
    puts filters
    applicable_filters = []
    if filters[:price_rng].present?
      if filters[:price_rng].to_i > 50
        applicable_filters.push(range: {price: { gte: 50 }})
      else
        applicable_filters.push(range: {price: { lte: filters[:price_rng].to_i }})
      end
    end
    if filters[:specialization].present?
      applicable_filters.push(terms: {'specializations.id'  => filters[:specialization].map{|i| i.to_i}})
    end

    if filters[:ratings].present?
      applicable_filters.push(range: {avg_rating: { lte: filters[:ratings].to_i }})
    end
    puts applicable_filters
    if applicable_filters.size > 0
      __elasticsearch__.search query: {
                                   filtered: {
                                       filter: {
                                           bool: {
                                               must: applicable_filters
                                           }
                                       }
                                   }
                               },
                               sort: [{sort_column => { order: sort_direction }}]
    else
      __elasticsearch__.search query: {match_all: {}},
                               sort: [{sort_column => { order: sort_direction }}]
    end
  end

end

Merchant.import force: true

app/models/opening.rb
class Opening < ActiveRecord::Base
  belongs_to :merchant
  enum status: [:booked, :available, :complete]


end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  has_and_belongs_to_many :merchants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :sort_column, :sort_direction

  def sort_column
    Merchant.column_names.include?(params[:sort]) ? params[:sort] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : 'asc'
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @merchant =  Merchant.filter(params, sort_column, sort_direction)
  end

  private
  # def apply_filter(params)
  #   if params[:specialization].present?
  #     @merchant = @merchant.where(specializations: {id: params[:specialization].map{|i| i.to_i}})
  #   end
  #   if params[:price_rng].present?
  #     if params[:price_rng].eql?('60')
  #       @merchant = @merchant.where('merchants.price > ?', 50)
  #     else
  #       @merchant = @merchant.where('merchants.price < ?',params[:price_rng])
  #     end
  #   end
  #   if params[:ratings].present?
  #     @merchant =  @merchant.where('merchants.avg_rating < ?', params[:ratings])
  #   end
  #   if params[:session_rng].present?
  #     if params[:session_rng].eql?('60')
  #       @merchant = @merchant.joins(:openings).where('(openings.end_time-openings.start_time) > INTERVAL ?', "50 minutes")
  #     else
  #       @merchant = @merchant.joins(:openings).where('(openings.end_time-openings.start_time) < INTERVAL ?', "#{params[:session_rng]} minutes")
  #     end
  #   end
  #   if params[:available].present?
  #     query = params[:available].split(',')
  #     if query.size == 1
  #       @merchant = @merchant.available.where('openings.start_time = ?', query[0])
  #     else
  #       @merchant = @merchant.available.where('openings.start_time >= ? and openings.start_time <= ?', query[0], query[1])
  #     end
  #   end
  # end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  skip_before_action :verify_authenticity_token, only: :suggest

  def search
    @merchant = []
    unless params[:q].nil?
      @merchant = Merchant.search(params[:q], sort_column, sort_direction)
    end
    render 'merchants/index'
  end

  def suggest
    merchant = []
    unless params[:q].nil?
      merchant = Merchant.suggest params[:q]
    end
    render json: merchant
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == sort_column && sort_direction == 'asc') ? 'desc' : 'asc'
    link_to title, request.parameters.except(:utf8).merge(sort: column, direction: direction)
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper

  def availability
    {Now:-> { Time.now }, Morning: -> { "#{Time.now.at_midday - 6.hours}, #{Time.now.at_midday}" }, Afternoon:-> { "#{Time.now.at_midday}, #{Time.now.at_midday + 4.hours}" },
             Evening:-> { "#{Time.now.at_midday + 4.hours}, #{Time.now.at_midday + 8.hours}" }, Night:-> { "#{Time.now.at_midday + 8.hours}, #{Time.now.end_of_day}" }, Today:-> { "#{Time.now.beginning_of_day}, #{Time.now.end_of_day}" },
             Tomorrow:-> { "#{Time.now.beginning_of_day + 1.day}, #{Time.now.end_of_day + 1.day}" }, 'This Week' => -> { "#{Time.now}, #{Time.now.end_of_week}" }}
  end

  def price_max
    params[:price_rng] || 60
  end
  def rating_max
    params[:ratings] || 5
  end
  def selected_spec
    params[:specialization] || []
  end
  def selected_avail
    params[:available] || []
  end
  def session_max
    params[:session_rng] || 60
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssignmentEros</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse  navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<% merchants_index_path %>>Eros</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
          <li><a href="#how_does_it_work">How does it works</a></li>
          <li><a href="#how_do_i_benefit">How do I benefit</a></li>
          <li class="navbar-form navbar-left">
            <%= form_tag search_path, method: :get do %>
                <%= text_field_tag :q, params[:q], class: 'typeahead' %>
                <%= submit_tag "Go" %>
            <% end %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div><!-- /.container -->
</body>
</html>

app/views/merchants/_index.html.erb
<%= render 'shared/sorting'%>
<div class="row">
  <%= render 'shared/sidebar'%>
  <div class="col-md-9 col-md-offset-3 content">
    <% unless @merchant.blank? %>
      <% @merchant.each do |merchant| %>
        <div class="panel panel-info">
          <div class="col-md-12 panel-heading">
            <span class="col-md-3"><%= merchant.name %></span>
            <span class="pull-right col-md-6">Rating: <%= merchant.avg_rating %></span>
          </div>
          <div class="panel-body">
            <p><%= merchant.about %></p>
            Specializations:
            <% if merchant.specializations.is_a? Array%>
              <%= merchant.specializations.map {|i| i.name}.join(',') %><br />
            <% else %>
              <%= merchant.specializations.pluck(:name).join(', ') %><br />
            <% end %>
            Price:<%= merchant.price %><br />
            Reviews: <%= merchant.review_count %><br/>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/merchants/index.html.erb
<%= render 'merchants/index'%>

app/views/shared/_sidebar.html.erb
<div class="col-md-3 sidebar">
  <%= form_tag merchants_index_path, :method => 'get', class: 'filter' do %>
    <div class="panel panel-default">
      <div class="panel-heading">Specializations</div>
      <div class="panel-body">
        <% Specialization.all.each do |a_value| %>
          <div>
          <%= label_tag a_value.name%>
          <%= check_box_tag "specialization[]", a_value.id, selected_spec.include?(a_value.id.to_s)%></div>
        <% end %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Price Per Session</div>
      <div class="panel-body">
        <%= text_field_tag :price_rng, price_max, data: {'slider-value' => price_max} %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Rating</div>
      <div class="panel-body">
        <%= text_field_tag :ratings, rating_max, data: {'slider-value' => rating_max} %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Session Length(min)</div>
      <div class="panel-body">
        <%= text_field_tag :session_rng, session_max, data: {'slider-value' => session_max}%>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Availability</div>
      <div class="panel-body">
        <% availability.each do |k,v| %>
          <div>
          <%= label_tag k %>
          <%= check_box_tag "available", v.call, selected_avail.include?(v.call.to_s) %></div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_sorting.html.erb
<div class="page-header pull-right">
  <span><%= sortable 'avg_rating', 'Rating' %></span>
  <span><%= sortable 'price', 'Price' %></span>
</div>